### ISSUE TITLE
dry refactoring

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#117]
DRY (dont repeat yourself) refactoring of a number of things would be useful.

- transition methods. more generic rpy2 functions rather than current approach that has a functin for every module.
- move some variables to us_utils that are repeatedly defined for no reason such as starting year of model. 
- any more reduction in boiler plate. intervention class that inherits base may be useful.

**Comment by ld-archer** [comment]
Prediction functions in r_utils have been refactored in #84, now have one function for each model type (OLS, CLM, etc.).

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: RobertClay ***@***.***>
Sent: Friday, January 13, 2023 3:11:55 PM
To: Leeds-MRG/Minos ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Leeds-MRG/Minos] dry refactoring (Issue #117)


DRY (dont repeat yourself) refactoring of a number of things would be useful.

  *   transition methods. more generic rpy2 functions rather than current approach that has a functin for every module.
  *   move some variables to us_utils that are repeatedly defined for no reason such as starting year of model.
  *   any more reduction in boiler plate. intervention class that inherits base may be useful.

**Comment by RobertClay** [comment]
refactoring done for estimate_transitions as well is very similar. reasonably happy with boilerplate for now. maybe an intervention class but very little gain..
