### ISSUE TITLE
interview times for time steps?

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#26]
Remove the time variables and replace with interview month/year. Depends on a few things.

- Want uniform time steps of approx one year. Are interviews recorded at roughly the same annual time. If so can probably do it by month. Could see interesting things with seasonality here (e.g. heater/depression much more important in the winter)
- May be much easier just rounding to 01/09 of the year and pretending it doesnt exist until we decide to implement (pseudo)continuous ageing.
- Can vivarium even handle this? Time steps are generally uniform steps but in theory it generalises to any "event" in continous time. See event manager docs for vivarium.

**Comment by RobertClay** [comment]
i think its at least including as a variable because it can time of year can be useful in predicting depression and or housing quality's effect on depression

**Comment by ld-archer** [comment]
Good point. I've written a function in US_utils that takes the year and month and mashes them together (i.e. 07/2012 becomes 201207) because that was the format required for the inflation adjustment. I'll write another that can convert back to a separate year and month variables. Might be a bit daft to keep the mashed variable instead of the two separate ones but at least its 1 less column.

**Comment by RobertClay** [comment]
gonna close this. just include it as a variable.
